### ISSUE TITLE
Update README and Farm docs with latest data

### ISSUE THREAD

**Issue by yyx990803** [farm-fe/performance-compare#14]
#11 was merged 5 days ago but the README of this repo and Farm's official website https://www.farmfe.org/ still displays inaccurate data about Vite's performance. Please update the relevant places where the data from this benchmark is displayed to avoid misleading users.

I didn't include the updates in #11 because I think it's best to use data from the same machine that generated the previous data.

**Comment by wre232114** [comment]
We'll update readme and official website today or tomorrow. Sorry, there is a lot of work to do...

**Comment by ErKeLost** [comment]
Sorry, the update is delayed. Now the readme and official website have switched to the latest data.

**Comment by wre232114** [comment]
All benchmark data generated on Linux Mint, 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz, 16GB

**Comment by ErKeLost** [comment]
The latest data has been updated
